services:
  mysql:
    image: mysql:8.0
    container_name: mysql_rms_db
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: rms_db
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "0.0.0.0"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Rms_Go
    environment:
      PORT: 0.0.0.0:3000
      JWT_SECRET: GoAppSecret
      ALLOWED_ORIGINS: "*"
      MYSQL_URL: root:password@tcp(mysql:3306)/rms_db
      API_KEY: ${API_KEY}
      API_URL: ${API_URL}
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c "
      cd src/database/migrations &&
      goose mysql 'root:password@tcp(mysql:3306)/rms_db' up &&
      cd ../../../ &&
      go build -o main . &&
      ./main
      "

volumes:
  mysql_data:
